### ISSUE TITLE
deploy of module failed

### ISSUE THREAD

**Issue by pdhaese** [qmatic/orchestra-events#3]
Hey,

I was deploying this module on my test system (orchestra 5.4 HF2) but the deploy always fails.
I did the gradlew clean build via cmd. everything looks fine. But when deploying something doesn't work.

 can you look into this?

I'll send you an extract of the logiles via mail. 

Best regards,

Pieter

**Comment by gavsmi** [comment]
Can you try downloading the war from the release page on GitHub and see if that deploys: https://github.com/qmatic/orchestra-events/releases/download/0.2.2/qp-events-0.2.2.war

**Comment by pdhaese** [comment]
I tried it out and the war file from the release page works fine.
thnanks.
